name: EhViewer

on: 
 push:
    branches:
    - master
 pull_request:
    branches:
    - master
 release:
    types:
    - created
jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        env:
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          ALIAS_NAME: ${{ secrets.ALIAS_NAME }}
          ALIAS_PASS: ${{ secrets.ALIAS_PASS }}
        run: |
          ./gradlew assembleRelease
      - name: Release
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/app-release.apk
      - uses: actions/upload-artifact@master
        name: Upload artifact
        with:
          name: EhViewer.apk
          path: app/build/outputs/apk/release/app-release.apk
